# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constrs_1/zedboard_constraints.xdc

# Block Designs: bd/votechain_1/votechain_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==votechain_1 || ORIG_REF_NAME==votechain_1} -quiet] -quiet

# IP: bd/votechain_1/ip/votechain_1_votechain1_0_1/votechain_1_votechain1_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==votechain_1_votechain1_0_1 || ORIG_REF_NAME==votechain_1_votechain1_0_1} -quiet] -quiet

# XDC: bd/votechain_1/ip/votechain_1_votechain1_0_1/src/votechain1_ooc.xdc

# XDC: bd/votechain_1/votechain_1_ooc.xdc
