# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/ESE 498_Capstone/Votechain/Votechain.srcs/sources_1/ip/currt_block/currt_block.xci
# IP: The module: 'currt_block' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/ESE 498_Capstone/Votechain/Votechain.srcs/sources_1/ip/currt_block/currt_block_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'currt_block'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: h:/ESE 498_Capstone/Votechain/Votechain.srcs/sources_1/ip/currt_block/currt_block.xci
# IP: The module: 'currt_block' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/ESE 498_Capstone/Votechain/Votechain.srcs/sources_1/ip/currt_block/currt_block_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'currt_block'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
