# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: zedboard_constraints.xdc

# Block Designs: bd/votechain1/votechain1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==votechain1 || ORIG_REF_NAME==votechain1} -quiet] -quiet

# IP: bd/votechain1/ip/votechain1_controller_0_0/votechain1_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==votechain1_controller_0_0 || ORIG_REF_NAME==votechain1_controller_0_0} -quiet] -quiet

# IP: bd/votechain1/ip/votechain1_BRAM_0_0/votechain1_BRAM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==votechain1_BRAM_0_0 || ORIG_REF_NAME==votechain1_BRAM_0_0} -quiet] -quiet

# IP: bd/votechain1/ip/votechain1_data_validation_0_0/votechain1_data_validation_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==votechain1_data_validation_0_0 || ORIG_REF_NAME==votechain1_data_validation_0_0} -quiet] -quiet

# IP: bd/votechain1/ip/votechain1_button_debounce_0_0/votechain1_button_debounce_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==votechain1_button_debounce_0_0 || ORIG_REF_NAME==votechain1_button_debounce_0_0} -quiet] -quiet

# IP: bd/votechain1/ip/votechain1_data_mining_0_0/votechain1_data_mining_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==votechain1_data_mining_0_0 || ORIG_REF_NAME==votechain1_data_mining_0_0} -quiet] -quiet

# XDC: bd/votechain1/votechain1_ooc.xdc
